name: Update Products and Deploy to AWS

on:
  # AUTOMATIC: Runs daily at 1 AM UTC
  schedule:
    - cron: '0 1 * * *'
  
  # AUTOMATIC: Runs when you push to main branch
  push:
    branches:
      - production
    paths:
      - 'scripts/**'
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'webpack.config.js'
      - 'webpack.*.js'
      - '.github/workflows/**'
  
  # MANUAL: Allows you to trigger manually anytime
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET: candid-findings  # CHANGE THIS to your bucket name!

jobs:
  update-and-deploy:
    name: Update Content & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: ðŸ“¦ Install dependencies
        run: npm ci
      
      - name: ðŸ›ï¸ Fetch Amazon products
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_PARTNER_TAG: ${{ secrets.AMAZON_PARTNER_TAG }}
        run: node scripts/fetch-products.js
        continue-on-error: true  # Don't fail if Amazon API not ready yet
      
      - name: ðŸ¤– Generate AI blog posts
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: node scripts/generate-blogs.js
        continue-on-error: true  # Don't fail if no products to blog about
      
      - name: ðŸ—ºï¸ Generate sitemap
        run: node scripts/generate-sitemap.js
        continue-on-error: true  # Don't fail if no blogs yet

      - name: ðŸ—ï¸ Build production site
        run: npm run build
      
      - name: ðŸ”‘ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: ðŸ“¤ Deploy to S3
        run: |
          echo "Uploading to S3..."
          
          # Upload all files except index.html, JSON, and sitemap with long cache
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }} \
            --delete \
            --cache-control "public, max-age=0, must-revalidate" \
            --exclude "index.html" \
            --exclude "*.json" \
            --exclude "data/*" \
            --exclude "sitemap.xml"
          
          # Upload index.html, JSON files, and sitemap with no cache (always fresh)
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }} \
            --cache-control "no-cache, no-store, must-revalidate" \
            --exclude "*" \
            --include "index.html" \
            --include "*.json" \
            --include "data/*" \
            --include "sitemap.xml"
          
          echo "âœ… S3 upload complete"
      
      - name: âš¡ Invalidate CloudFront cache (if configured)
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          if [ -n "$DISTRIBUTION_ID" ]; then
            echo "ðŸ”„ Invalidating CloudFront cache..."
            aws cloudfront create-invalidation \
              --distribution-id $DISTRIBUTION_ID \
              --paths "/*"
            echo "âœ… CloudFront invalidation triggered"
          else
            echo "â„¹ï¸  CloudFront not configured, skipping cache invalidation"
          fi

      - name: ðŸ“Š Deployment summary
        if: always()
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          echo ""
          echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
          echo "ðŸ“¦ DEPLOYMENT SUMMARY"
          echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
          echo ""
          echo "Status: ${{ job.status }}"
          echo "Bucket: ${{ env.S3_BUCKET }}"
          echo "Region: ${{ env.AWS_REGION }}"
          echo "Time: $(date +'%Y-%m-%d %H:%M:%S UTC')"
          echo ""
          echo "ðŸŒ Check your site:"
          if [ -n "$DISTRIBUTION_ID" ]; then
            echo "   CloudFront: https://[your-distribution].cloudfront.net"
          fi
          echo "   S3 Website: http://${{ env.S3_BUCKET }}.s3-website-${{ env.AWS_REGION }}.amazonaws.com"
          echo ""
          echo "ðŸ—ºï¸ Sitemap: https://candidfindings.com/sitemap.xml"
          echo ""
          echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"

      - name: Check for changes
        id: verify_diff
        run: |
          git diff --quiet public/data/blogs.json || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config us "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/blogs.json
          git commit -m "ðŸ¤– Update products - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
      
      - name: No changes detected
        if: steps.verify_diff.outputs.changed != 'true'
        run: |
          echo "âœ“ No changes to blogs.json file - skipping commit"